stages:
  - test
pytest:
  stage: test
  image: python:3.11
  script:
    - pip install -r requirements.txt
    - python -m pytest --junitxml=junit.xml
  artifacts:
    reports:
      junit: junit.xml
  
deployment:
  stage: deploy
  script:
    - curl <your deploy hook copied from render.com>
  only:
    - main